### ISSUE TITLE
S_SPAWN_DROPITEM.8 deprecated definition (e.g. in Draakon Arena NM)

### ISSUE THREAD

**Issue by Shiriko-star** [Multarix/tera-guide-revised#4]
Perhaps it's a Toolbox initiative with Patch 99. Console errors complaining of S_SPAWN_DROPITEM.8 deprecated definition, upon doing DAN and probably other dungeons. 

HSDN's Tera guide has the same issue.

**Comment by Shiriko-star** [comment]
https://i.imgur.com/Z34jVeY.png

Image of log

**Comment by Multarix** [comment]
This was indeed related to toolbox updating it's defs as seen here, thanks for alerting me to this!
![image](https://user-images.githubusercontent.com/29752805/96041399-19cf1700-0eaf-11eb-9053-60267f703f3e.png)

**Comment by justkeepquiet** [comment]
Hi. Your fix https://github.com/Multarix/tera-guide-revised/commit/a7504480bd8610a36968e900bd00d326d34996ef is not correct because some regions still have patch 98. 
You need to consider the `mod.majorPatchVersion` when changing the package version. 
Like this: https://github.com/hsdn/tera-guide-core/blob/a14a354d11dd7c3760d1615c79c5b92e1b5a538b/lib/core/events/handlers/spawn.js#L107

**Comment by Multarix** [comment]
Blame EME for deciding to not exist and do nothing until November, it's rather pointless as well when almost nobody on NA is doing dungeons and won't be doing dungeons till after the transfer.
